project_id = "iralfqlslqndgvexixis"

[functions.proxy-stt]
verify_jwt = false

[functions.proxy-llm]
verify_jwt = false

[functions.proxy-tts]
verify_jwt = false

[functions.sync-notion]
verify_jwt = false

[functions.query-rag]
verify_jwt = false

[functions.rewrite-query]
verify_jwt = false

[functions.summarize-session]
verify_jwt = false
