import type { ConversationTurnTraceV1 } from "@/types";

export function makeConversationTraceV1(longPrompt = `SYSTEM ${"x".repeat(4_000)}`): ConversationTurnTraceV1 {
  const messages = [
    { role: "system" as const, content: longPrompt },
    { role: "user" as const, content: "Où est Ava ?" },
  ];
  return {
    schemaVersion: 1,
    identity: {
      sessionId: "session-trace",
      turnId: "turn-trace-1",
      turnIndex: 1,
      characterName: "Max",
      createdAt: "2026-08-04T10:00:00.000Z",
      status: "causal_complete",
    },
    input: { userMessage: "Où est Ava ?" },
    memory: {
      totalHistoryMessages: 0,
      selectedHistory: [],
      sessionSummary: null,
      summaryLastTurn: 0,
      userRoleSummary: null,
      userPostureRaw: null,
      postVideoContext: null,
      temporalContext: { timeElapsedSeconds: 12, sessionDurationSeconds: 930, turnIndex: 1 },
      gmGuidance: null,
      gmTopicsCovered: [],
    },
    rag: {
      request: {
        userMessage: "Où est Ava ?",
        recentContext: "",
        rewrittenQuery: null,
        searchInput: "Où est Ava ?",
        matchCount: 5,
        retrieveK: 15,
        matchThreshold: 0.3,
        characterId: "max-id",
        provider: "voyage",
        rerankRequested: true,
      },
      matches: [],
      formattedContext: "",
      knowledgeContext: {
        allowedFacts: [],
        activeMemories: [],
        hypotheses: [],
        forbiddenTopics: [],
        blockedAssertions: [],
      },
      embeddingProvider: "voyage",
      rerankUsed: true,
      error: null,
      serverLatencyMs: 4,
    },
    prompt: {
      baseSystemPrompt: longPrompt,
      baseSource: { kind: "database", characterId: "max-id", canonicalName: "Max", updatedAt: null },
      characterPrompt: { characterId: "max-id", canonicalName: "Max", updatedAt: null, renderedSections: longPrompt },
      technicalRules: "Règles techniques",
      injectedSections: [{ key: "rag", title: "RAG", content: longPrompt }],
      finalSystemPrompt: longPrompt,
    },
    maxCall: {
      messages,
      diagnostic: {
        clientPayload: { model: "openai/gpt-4.1-mini", messages, max_tokens: 120 },
        upstreamPayload: { model: "openai/gpt-4.1-mini", messages, temperature: 0.7, max_tokens: 120 },
        requestedModel: "openai/gpt-4.1-mini",
        returnedModel: "openai/gpt-4.1-mini",
        provider: "OpenAI",
        generationId: "generation-1",
        usage: { prompt_tokens: 50, completion_tokens: 8, total_tokens: 58 },
        upstreamLatencyMs: 120,
        proxyLatencyMs: 125,
      },
      requestedSettings: {
        model: "openai/gpt-4.1-mini",
        temperature: 0.7,
        maxTokens: 120,
        topP: 0.9,
        reasoning: false,
        timeoutMs: 8_000,
      },
      error: null,
    },
    response: { rawLlmResponse: "Elle est à Lausanne.", deliveredResponse: "Elle est à Lausanne.", source: "llm" },
    gm: {
      causalGuidance: { guidance: null, topicsCovered: [], source: "none" },
      preTurnPlanner: { status: "not_executed", reason: "disabled_in_prd4_live" },
      validator: { status: "not_executed", reason: "disabled_in_prd4_live" },
      labelPass: { status: "pending" },
      postTurn: { status: "pending" },
    },
    timings: {
      summaryFetchMs: 1,
      ragMs: 4,
      promptBuildMs: 2,
      maxClientMs: 130,
      maxProxyMs: 125,
      maxUpstreamMs: 120,
      pipelineUninstrumentedMs: 3,
      coreTotalMs: 140,
      traceWriteMs: null,
      observedTotalMs: 140,
    },
  };
}
