// @vitest-environment node
import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { PGlite } from "@electric-sql/pglite";

const PROD_USER = "11111111-1111-4111-8111-111111111111";

describe("v0.26 environments migration", () => {
  let db: PGlite;

  beforeEach(async () => {
    db = new PGlite();
    await db.exec(`
      create role anon;
      create role authenticated;
      create role service_role;
      create schema auth;
      create table auth.users (id uuid primary key, email text);
      insert into auth.users values ('${PROD_USER}', 'info@memoways.com');
      create function auth.uid() returns uuid language sql stable
        as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
      create function auth.jwt() returns jsonb language sql stable
        as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
      grant usage on schema auth to anon, authenticated, service_role;
      grant execute on function auth.uid(), auth.jwt() to anon, authenticated, service_role;

      create type public.app_role as enum ('admin');
      create table public.user_roles (
        id uuid primary key default gen_random_uuid(),
        user_id uuid not null references auth.users(id) on delete cascade,
        role public.app_role not null,
        created_at timestamptz not null default now(),
        unique (user_id, role)
      );
      create table public.admin_settings (
        key text primary key,
        value jsonb not null default '{}'::jsonb,
        updated_at timestamptz not null default now()
      );
      insert into public.admin_settings (key, value) values ('ava_tts_settings', '{"provider":"elevenlabs"}');
      alter table public.admin_settings enable row level security;

      create table public.characters (
        id uuid primary key default gen_random_uuid(),
        name text not null
      );
      insert into public.characters (name) values ('Max Lorenzo');
      create table public.character_prompts (
        character_id uuid primary key references public.characters(id) on delete cascade,
        identite_fondamentale text not null default '',
        qui_tu_es text not null default '',
        ce_que_tu_ne_fais_jamais text not null default '',
        ce_que_tu_sais_utilisateur text not null default '',
        dynamique_conversation text not null default '',
        sujets_sensibles text not null default '',
        profondeur_par_niveau text not null default '',
        timeline text not null default '',
        situation_summary text not null default '',
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
      insert into public.character_prompts (character_id, identite_fondamentale)
        select id, 'Max prod' from public.characters;
      alter table public.character_prompts enable row level security;
      create policy "character_prompts_read_all" on public.character_prompts for select using (true);

      create table public.character_runtime_profiles (
        id uuid primary key default gen_random_uuid(),
        character_key text not null unique,
        display_name text not null,
        enabled boolean not null default false,
        notion_character_id uuid references public.characters(id),
        opening_line text,
        portrait_url text,
        tts_provider text,
        tts_voice_id text,
        prompt_validated boolean not null default false,
        rag_validated boolean not null default false,
        qualitative_tests_validated boolean not null default false,
        knowledge_isolation_validated boolean not null default false,
        metadata jsonb not null default '{}'::jsonb,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
      insert into public.character_runtime_profiles (character_key, display_name, enabled)
        values ('max', 'Max', true), ('emma', 'Emma', false);
      alter table public.character_runtime_profiles enable row level security;

      create table public.experience_orchestration_versions (
        id uuid primary key default gen_random_uuid(),
        version_number bigint generated by default as identity unique,
        status text not null default 'draft',
        name text not null default 'GM',
        prompt text not null,
        config jsonb not null default '{}'::jsonb,
        source_version_id uuid references public.experience_orchestration_versions(id),
        created_by uuid references auth.users(id),
        published_at timestamptz,
        archived_at timestamptz,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
      create unique index experience_orchestration_one_published_idx
        on public.experience_orchestration_versions ((status)) where status = 'published';
      insert into public.experience_orchestration_versions (status, name, prompt, published_at)
        values ('published', 'Baseline', 'builtin://experience-director/v1', now());

      create table public.sessions (
        id uuid primary key default gen_random_uuid(),
        user_id uuid references auth.users(id) default auth.uid(),
        started_at timestamptz default now(),
        orchestration_version_id uuid references public.experience_orchestration_versions(id)
      );
      alter table public.sessions enable row level security;
    `);

    const migrationUrl = new URL(
      "../../supabase/migrations/20260821120000_settings_environments_admin_users.sql",
      import.meta.url,
    );
    const migration = await readFile(migrationUrl, "utf8");
    await db.exec(migration);
    await db.exec(migration);
  }, 30_000);

  afterEach(async () => db.close());

  it("seeds exactly four environments and backfills production settings", async () => {
    const environments = await db.query<{ id: string }>("select id from public.environments order by id");
    expect(environments.rows.map((row) => row.id)).toEqual([
      "prod", "sandbox-benoit", "sandbox-romed", "sandbox-ulrich",
    ]);
    const settings = await db.query<{ environment_id: string }>("select environment_id from public.admin_settings");
    expect(settings.rows).toEqual([{ environment_id: "prod" }]);
    const prompts = await db.query<{ environment_id: string }>("select environment_id from public.character_prompts");
    expect(prompts.rows).toEqual([{ environment_id: "prod" }]);
    const profiles = await db.query<{ count: number }>("select count(*)::int as count from public.character_runtime_profiles");
    expect(profiles.rows[0]?.count).toBe(8);
  });

  it("enrolls named accounts and creates one published GM baseline per environment", async () => {
    const members = await db.query<{ display_name: string; default_environment_id: string }>(
      "select display_name, default_environment_id from public.admin_users",
    );
    expect(members.rows).toEqual([{ display_name: "Production", default_environment_id: "prod" }]);
    const published = await db.query<{ environment_id: string }>(
      "select environment_id from public.experience_orchestration_versions where status = 'published' order by environment_id",
    );
    expect(published.rows.map((row) => row.environment_id)).toEqual([
      "prod", "sandbox-benoit", "sandbox-romed", "sandbox-ulrich",
    ]);
  });

  it("locks public sessions to prod and attributes member sandbox sessions", async () => {
    await db.exec(`
      update public.character_runtime_profiles
      set tts_provider = case when environment_id = 'sandbox-benoit' then 'sandbox-provider' else 'prod-provider' end
      where character_key = 'max';
      insert into auth.users (id, email)
      values ('22222222-2222-4222-8222-222222222222', 'visitor@example.com');
      select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', false);
    `);
    const publicSession = await db.query<{
      environment_id: string;
      context_type: string;
      started_by_user_id: string | null;
    }>(`
      insert into public.sessions (environment_id, campaign_id)
      values ('sandbox-benoit', 'user-tests-sept-2026')
      returning environment_id, context_type, started_by_user_id
    `);
    expect(publicSession.rows[0]).toEqual({
      environment_id: "prod",
      context_type: "user_test",
      started_by_user_id: null,
    });
    const publicProfile = await db.query<{ tts_provider: string }>(`
      select tts_provider
      from public.get_character_runtime_readiness_for_environment('max', 'sandbox-benoit')
    `);
    expect(publicProfile.rows[0]?.tts_provider).toBe("prod-provider");
    await db.exec("alter table public.sessions disable row level security; set role authenticated");
    await expect(db.exec(`
      update public.sessions
      set environment_id = 'sandbox-benoit', context_type = 'sandbox'
      where environment_id = 'prod'
    `)).rejects.toThrow("session attribution fields cannot be changed");
    await db.exec("reset role; alter table public.sessions enable row level security");

    await db.query("select set_config('request.jwt.claim.sub', $1, false)", [PROD_USER]);
    const memberProfile = await db.query<{ tts_provider: string }>(`
      select tts_provider
      from public.get_character_runtime_readiness_for_environment('max', 'sandbox-benoit')
    `);
    expect(memberProfile.rows[0]?.tts_provider).toBe("sandbox-provider");
    const memberSession = await db.query<{
      environment_id: string;
      context_type: string;
      started_by_user_id: string | null;
    }>(`
      insert into public.sessions (environment_id)
      values ('sandbox-romed')
      returning environment_id, context_type, started_by_user_id
    `);
    expect(memberSession.rows[0]).toEqual({
      environment_id: "sandbox-romed",
      context_type: "sandbox",
      started_by_user_id: PROD_USER,
    });
  });

  it("never exposes the password or sandbox settings to the anon role", async () => {
    await db.exec(`
      insert into public.admin_settings (key, value, environment_id) values
        ('public_access.password', '{"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}', 'prod'),
        ('ava_tts_settings', '{"provider":"gradium"}', 'sandbox-benoit');
      insert into public.character_prompts (character_id, identite_fondamentale, environment_id)
        select id, 'Sandbox secret', 'sandbox-benoit' from public.characters;
      set role anon;
    `);
    const visible = await db.query<{ key: string; environment_id: string }>(
      "select key, environment_id from public.admin_settings order by key, environment_id",
    );
    expect(visible.rows).toEqual([{ key: "ava_tts_settings", environment_id: "prod" }]);
    const visiblePrompts = await db.query<{ environment_id: string }>(
      "select environment_id from public.character_prompts order by environment_id",
    );
    expect(visiblePrompts.rows).toEqual([{ environment_id: "prod" }]);
  });
});
