-- Expérience Director / handoff foundations.
-- Additive only: historical GM columns and logs remain available during the
-- compatibility window. Apply exclusively through Lovable Cloud.

CREATE TABLE IF NOT EXISTS public.experience_orchestration_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  name text NOT NULL DEFAULT 'Orchestration GM',
  prompt text NOT NULL,
  config jsonb NOT NULL DEFAULT '{"schemaVersion":1,"minimumHandoffTurn":4,"maximumHandoffsPerSession":1,"handoffTarget":"emma","directorTimeoutMs":12000}'::jsonb,
  source_version_id uuid REFERENCES public.experience_orchestration_versions(id) ON DELETE SET NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS experience_orchestration_one_published_idx
  ON public.experience_orchestration_versions ((status))
  WHERE status = 'published';

INSERT INTO public.experience_orchestration_versions (
  status, name, prompt, config, published_at
)
SELECT
  'published',
  'Baseline PRD4 intégrée',
  'builtin://experience-director/v1',
  '{"schemaVersion":1,"minimumHandoffTurn":4,"maximumHandoffsPerSession":1,"handoffTarget":"emma","directorTimeoutMs":12000}'::jsonb,
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM public.experience_orchestration_versions WHERE status = 'published'
);

CREATE TABLE IF NOT EXISTS public.character_runtime_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  character_key text NOT NULL UNIQUE CHECK (character_key IN ('max', 'emma')),
  display_name text NOT NULL,
  enabled boolean NOT NULL DEFAULT false,
  notion_character_id uuid REFERENCES public.characters(id) ON DELETE SET NULL,
  opening_line text,
  portrait_url text,
  tts_provider text,
  tts_voice_id text,
  prompt_validated boolean NOT NULL DEFAULT false,
  rag_validated boolean NOT NULL DEFAULT false,
  qualitative_tests_validated boolean NOT NULL DEFAULT false,
  knowledge_isolation_validated boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.character_runtime_profiles (character_key, display_name, enabled)
VALUES ('max', 'Max', true), ('emma', 'Emma', false)
ON CONFLICT (character_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.experience_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
  event_key text NOT NULL,
  event_type text NOT NULL,
  turn_id text,
  turn_index integer,
  character_key text CHECK (character_key IS NULL OR character_key IN ('max', 'emma')),
  orchestration_version_id uuid REFERENCES public.experience_orchestration_versions(id) ON DELETE SET NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, event_key)
);

CREATE TABLE IF NOT EXISTS public.admin_legacy_access_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tab text NOT NULL CHECK (tab IN ('validator', 'metrics')),
  accessed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS experience_events_session_created_idx
  ON public.experience_events (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS experience_events_type_created_idx
  ON public.experience_events (event_type, created_at DESC);

ALTER TABLE public.sessions
  ADD COLUMN IF NOT EXISTS orchestration_version_id uuid
    REFERENCES public.experience_orchestration_versions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS active_character text NOT NULL DEFAULT 'max'
    CHECK (active_character IN ('max', 'emma')),
  ADD COLUMN IF NOT EXISTS pending_handoff jsonb,
  ADD COLUMN IF NOT EXISTS handoff_count integer NOT NULL DEFAULT 0
    CHECK (handoff_count >= 0 AND handoff_count <= 1);

ALTER TABLE public.sessions
  ALTER COLUMN conversation_memory SET DEFAULT '{"version":2,"lastTurn":0,"interlocutor":{"name":null,"role":null,"traits":[]},"userFacts":[],"maxDisclosures":[],"commitments":[],"openThreads":[],"topics":[],"relationship":{"depth":"surface","trust":"neutre","emotionalState":null,"sourceTurn":0},"lastExchange":null,"characterItems":[]}'::jsonb;

ALTER TABLE public.experience_orchestration_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.character_runtime_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_legacy_access_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage orchestration versions" ON public.experience_orchestration_versions;
CREATE POLICY "Admins manage orchestration versions"
  ON public.experience_orchestration_versions FOR ALL TO authenticated
  USING ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)))
  WITH CHECK ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)));

DROP POLICY IF EXISTS "Admins manage character runtime profiles" ON public.character_runtime_profiles;
CREATE POLICY "Admins manage character runtime profiles"
  ON public.character_runtime_profiles FOR ALL TO authenticated
  USING ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)))
  WITH CHECK ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)));

DROP POLICY IF EXISTS "Session owners append experience events" ON public.experience_events;
CREATE POLICY "Session owners append experience events"
  ON public.experience_events FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.sessions s
      WHERE s.id = session_id AND s.user_id = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS "Admins read experience events" ON public.experience_events;
CREATE POLICY "Admins read experience events"
  ON public.experience_events FOR SELECT TO authenticated
  USING ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)));

DROP POLICY IF EXISTS "Admins log legacy access" ON public.admin_legacy_access_log;
CREATE POLICY "Admins log legacy access"
  ON public.admin_legacy_access_log FOR INSERT TO authenticated
  WITH CHECK (
    user_id = (SELECT auth.uid())
    AND (SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role))
  );

DROP POLICY IF EXISTS "Admins read legacy access" ON public.admin_legacy_access_log;
CREATE POLICY "Admins read legacy access"
  ON public.admin_legacy_access_log FOR SELECT TO authenticated
  USING ((SELECT private.has_role((SELECT auth.uid()), 'admin'::public.app_role)));

-- No UPDATE/DELETE policy is intentionally defined: the event stream is append-only.

CREATE OR REPLACE FUNCTION public.pin_current_orchestration_version(p_session_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_version_id uuid;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication required';
  END IF;

  SELECT orchestration_version_id INTO v_version_id
  FROM public.sessions
  WHERE id = p_session_id AND user_id = v_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'session not found';
  END IF;

  IF v_version_id IS NULL THEN
    SELECT id INTO v_version_id
    FROM public.experience_orchestration_versions
    WHERE status = 'published'
    ORDER BY published_at DESC NULLS LAST, version_number DESC
    LIMIT 1;

    UPDATE public.sessions
      SET orchestration_version_id = v_version_id
      WHERE id = p_session_id
        AND user_id = v_user_id
        AND orchestration_version_id IS NULL;
  END IF;

  RETURN v_version_id;
END;
$$;

REVOKE ALL ON FUNCTION public.pin_current_orchestration_version(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pin_current_orchestration_version(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_pinned_orchestration_runtime(p_session_id uuid)
RETURNS TABLE (version_id uuid, version_number bigint, prompt text, config jsonb)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT v.id, v.version_number, v.prompt, v.config
  FROM public.sessions s
  JOIN public.experience_orchestration_versions v
    ON v.id = s.orchestration_version_id
  WHERE s.id = p_session_id
    AND s.user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.get_pinned_orchestration_runtime(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_pinned_orchestration_runtime(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.publish_experience_orchestration_version(p_version_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private, pg_temp
AS $$
BEGIN
  IF NOT private.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.experience_orchestration_versions
    WHERE id = p_version_id AND status = 'draft'
  ) THEN
    RAISE EXCEPTION 'publishable version not found';
  END IF;

  UPDATE public.experience_orchestration_versions
    SET status = 'archived', archived_at = now(), updated_at = now()
    WHERE status = 'published' AND id <> p_version_id;

  UPDATE public.experience_orchestration_versions
    SET status = 'published', published_at = now(), archived_at = NULL, updated_at = now()
    WHERE id = p_version_id;

  RETURN p_version_id;
END;
$$;

REVOKE ALL ON FUNCTION public.publish_experience_orchestration_version(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.publish_experience_orchestration_version(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_character_runtime_readiness(p_character_key text)
RETURNS TABLE (
  character_key text,
  display_name text,
  ready boolean,
  opening_line text,
  tts_provider text,
  tts_voice_id text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    p.character_key,
    p.display_name,
    (
      p.enabled
      AND p.notion_character_id IS NOT NULL
      AND length(coalesce(p.opening_line, '')) > 0
      AND length(coalesce(p.portrait_url, '')) > 0
      AND length(coalesce(p.tts_provider, '')) > 0
      AND length(coalesce(p.tts_voice_id, '')) > 0
      AND p.prompt_validated
      AND p.rag_validated
      AND p.qualitative_tests_validated
      AND p.knowledge_isolation_validated
    ) AS ready,
    p.opening_line,
    p.tts_provider,
    p.tts_voice_id
  FROM public.character_runtime_profiles p
  WHERE p.character_key = lower(p_character_key)
    AND auth.uid() IS NOT NULL;
$$;

REVOKE ALL ON FUNCTION public.get_character_runtime_readiness(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_character_runtime_readiness(text) TO authenticated;

COMMENT ON TABLE public.experience_orchestration_versions IS
  'Versioned draft/test/publish governance for the PRD4 Experience Director.';
COMMENT ON TABLE public.experience_events IS
  'Append-only idempotent experience actions and deterministic guard outcomes.';
COMMENT ON COLUMN public.sessions.orchestration_version_id IS
  'Published GM version pinned once at session start; never changed by later publications.';
COMMENT ON COLUMN public.sessions.pending_handoff IS
  'Serialized Max→Emma offer state used to resume the same session and timer.';
